spring.datasource.url=jdbc:mysql://gateway01.ap-southeast-1.prod.aws.tidbcloud.com:4000/test?sslMode=VERIFY_IDENTITY&enabledTLSProtocols=TLSv1.2&serverTimezone=UTC
spring.datasource.username=3Mdjt3XX3Mm3Qok.root
spring.datasource.password=ise4oP6lViDuJY3B
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
# 3. Auto-build the tables in the cloud
spring.jpa.hibernate.ddl-auto=update

# Keep your JWT secret and server port down here...
spring.security.user.password=12345
spring.security.user.name=admin